### ISSUE TITLE
NewTek NDI (virtual camera) crashes Stride

### ISSUE THREAD

**Issue by mhusinsky** [vvvv/VL.Video.MediaFoundation#10]
hey,

on my setup the NewTek NDI virtual camera (that is installed with the NDI Tools) crashes Stride when loading the VideoIn node. Unfortunately this cam seems to be my default device, therefore I can only create the node (or open the "capture" help patch) with the runtime stopped (F8) and then I have to chose another cam.

the crash acutally looks like this:
* patch stays responsive
* stride renderwindow hangs and is unresponsive
* trying to quit VVVV (or close the patch) does not work -> vvvv process has to be killed in the task manager

this is with 21.4.0228 alpha

**Comment by azeno** [comment]
Does the default windows camera app work?

**Comment by mhusinsky** [comment]
just gave it a test:
it does not "work" in the way that i can get an image from NDI (while in other apps like OBS i can), but it also does not crash the camera app

**Comment by azeno** [comment]
Hmm hard to say would need to reproduce on my end - can I?

**Comment by mhusinsky** [comment]
i was just about to write down the steps to reproduce when i noticed that a new version of NDI Tools (version 5) was released. with this version, webcam input appears to work fine with mediafoundation. this issue is therefore obsolete. thanks anyway!

**Comment by mhusinsky** [comment]
sorry - need to reopen this.
all only works fine when the NDI webcam input is actually up and running (this is a separate app where the sources of the virtual camera are managed). when this app is not running the stride renderer is in a "limbo" state (i.e. the patch stays responsive but the renderer blocks and also prevents vvvv from shutting down on quit. however, it is not dead but seems to wait for further frames - see below).

here's how to reproduce this:
* install NDI Tools 5. this installs a bunch of applications, among them
  * webcam input: the app that handles the sources to be displayed in the virtual webcam input (appearing as "NewTek NDI Video" webcam source). webcam input runs as a system tray app -> rightclick to configure the source to be forwarded. 
  * sources: to quickly get a source to be displayed, either run "test patterns" which creates classic test patterns as a source. alternatively the app "screen capture" forwards your screen as an NDI source
* run the vl.video.mediafoundation videoin helppatch and select the NDI video as source
   * when "webcam input" is running, everything is fine
   * when exiting "webcam input" (by right-clicking the system tray app -> exit), the vvvv patch stays responsive while the stride renderer enters the limbo state. one can even close the patch, however the renderer will stay and also prevent vvvv from shutting down on quit. it appears to wait for further frames because
     * in this state, when starting "webcam input" again, the stride renderer closes (because it's patch has been closed already)

**Comment by azeno** [comment]
Thanks. It gets stuck in the second call to `ReadSample`. The first call says there was a time gap, but I think that's normal. So I couldn't find a proper way to detect this case. Also calling `Flush` on the main thread on shutdown just lead to `Flush` being stuck. In the end I added a timeout of 500ms the system will wait on the video capture thread until it simply gives up. Leaving the "ghost" thread stuck in its ReadSample to its own demise.
