### ISSUE TITLE
Incorrect outcome in the VideoPlayer node

### ISSUE THREAD

**Issue by hameleon-ed** [vvvv/VL.Video.MediaFoundation#7]
Currently, the VideoPlayer node in VL output correctly only horizontal video like 1920x1080. Instead of that outcome texture for square videos or vertical videos look like video lines shifted. I tried several not horizontal videos and all of them shown incorrect texture.

**Comment by joreg** [comment]
any chance you could provide test videos for download that don't work for you?

**Comment by hameleon-ed** [comment]
For example https://www.dropbox.com/s/zmwsl2v89glb19o/ArchGAN_skyscraper_03_white_1.mp4?dl=0

**Comment by joreg** [comment]
perfect, thanks. i tested the video and it works for me. please make sure to test with the latest version!

Note that latest [vvvv gamma 2021.4 previews](https://visualprogramming.net/#Download) are already shipping with this nuget. please confirm you tested with this and not an older version.

**Comment by hameleon-ed** [comment]
I installed VL.Video.MediaFoundation 0.0.7-alpha instead VL.MediaFoundation 0.3.0-stride for VL 2021.331 (preview version doesn't work correctly with others nodes) and it works. Thank you!

**Comment by joreg** [comment]
thanks for following up!
